# This is a basic workflow to help you get started with Actions 

name: CI
on:
  push:
    branches: [ estudo-de-caso ]
    paths: [ '**.ipynb' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test-case-gradient-descent:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      ORCID_CLIENT_ID: ${{ secrets.ORCID_CLIENT_ID }}
      ORCID_CLIENT_SECRET: ${{ secrets.ORCID_CLIENT_SECRET }}
      ORCID_TOKEN: ${{ secrets.ORCID_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install simplejson
          pip install pandas
          pip install matplotlib
          pip install pytest
          pip install pytest-cov
          pip install IPython
      - name: Running a test case  
        run: |
          echo "Running the test case [Gradient descent]"
          pytest -v testcase.py 
      - name: Creating a test report and Commit files
        run: |
          echo "Creating a test report" 
          python testcase2.py
          cat results.html
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add results.html
          git commit -m "updated test report" results.html
          NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: estudo-de-caso
          github_token: ${{ secrets.GITHUB_TOKEN }}
