# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ estudo-de-caso ]
    paths: [ '**.ipynb' ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test-case-gradient-descent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running a test case  
        run: |
          echo "Running the test case [Gradient descent]"
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do        
            python3 cat_ipynb.py ${added_modified_file} > ${added_modified_file}__.py
          done
