# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ estudo-de-caso ]
    paths: [ '**.ipynb' ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test-case-gradient-descent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/test-case-gradient-descent@v1
      - name: Running a test case  
        run: |
          echo "Running the test case [Gradient descent]"
